name: dynamic_theme
description: Changes the theme during runtime, also presists brightness settings across restarts
version: 1.0.1
author: 'Norbert Kozsir <kozsir.norbert@gmail.com>'
homepage: 'https://github.com/Norbert515/dynamic_theme'

environment:
  # Works in Dart 1 (starting with 1.20.1), and works in Dart 2.
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.4+8
dev_dependencies:
  flutter_test:
    sdk: flutter
